general {
    immediate_render = true
}

background {
    monitor =
    path = ~/Pictures/wallpapers/Haus.png
    blur_passes = 2
    blur_size = 6
    brightness = 0.42
    contrast = 0.92
    vibrancy = 0.12
}

input-field {
    monitor =
    size = 300, 30
    outline_thickness = 1

    dots_size = 0.25
    dots_spacing = 0.55
    dots_center = true
    dots_rounding = -1

    outer_color = rgba(255, 255, 255, 0.28)
    inner_color = rgba(20, 20, 25, 0.52)
    font_color = rgba(242, 243, 244, 0.75)

    fade_on_empty = false
    placeholder_text = Enter Password
    hide_input = false

    check_color = rgba(204, 136, 34, 0)
    fail_color = rgba(204, 34, 34, 0)
    fail_text = $FAIL <b>($ATTEMPTS)</b>
    fail_transition = 300

    capslock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false

    position = 0, -468
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %B %d")"
    color = rgba(242, 243, 244, 0.75)
    font_size = 20
    font_family = sans-serif
    font_weight = bold
    position = 0, 405
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%k:%M")"
    color = rgba(242, 243, 244, 0.75)
    font_size = 93
    font_family = sans-serif
    font_weight = bold
    position = 0, 310
    halign = center
    valign = center
}

# Username
label {
    monitor =
    text = $USER
    color = rgba(242, 243, 244, 0.75)
    font_size = 12
    font_family = sans-serif
    font_weight = medium
    position = 0, -407
    halign = center
    valign = center
}

# Password prompt
label {
    monitor =
    text = Enter Password
    color = rgba(242, 243, 244, 0.75)
    font_size = 10
    font_family = sans-serif
    position = 0, -438
    halign = center
    valign = center
}


