profile {
    time = 07:00
    temperature = 6000
    gamma = 1.0
}

profile {
    time = 18:00
    temperature = 5000
    gamma = 0.95
}

profile {
    time = 21:30
    temperature = 4200
    gamma = 0.90
}

profile {
    time = 23:00
    temperature = 3500
    gamma = 0.85
}

