#!/usr/bin/env bash

if pidof -x $(basename "$0") -o %PPID >/dev/null; then
  exit
fi

main() {
  sleep 0.001
  clear

  local list=(
    "Lock"
    "Shutdown"
    "Reboot"
    "Logout"
    "Hibernate"
    "Suspend"
  )

  local options=(
    "--border=sharp"
    "--border-label= Power Menu "
    "--height=~100%"
    "--highlight-line"
    "--no-input"
    "--pointer="
    "--reverse"
    "--color=bg+:#d4be98,fg+:#1d2021,bg:#1d2021,fg:#d4be98"
  )

  local selected
  selected=$(printf "%s\n" "${list[@]}" | fzf "${options[@]}")

  case $selected in
  Lock) loginctl lock-session ;;
  Shutdown) systemctl poweroff ;;
  Reboot) systemctl reboot ;;
  Logout) loginctl terminate-session "$XDG_SESSION_ID" ;;
  Hibernate) systemctl hibernate ;;
  Suspend) systemctl suspend ;;
  *) exit 1 ;;
  esac
}

main
